//
// CenteredtextAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class CenteredtextAPI {
    /**
     * enum for parameter prefer
     */
    public enum Prefer_centeredtextDelete: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter centeredId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter text: (query)  (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func centeredtextDelete(centeredId: String? = nil, scriptId: String? = nil, text: String? = nil, prefer: Prefer_centeredtextDelete? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        centeredtextDeleteWithRequestBuilder(centeredId: centeredId, scriptId: scriptId, text: text, prefer: prefer).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /centeredtext
     - 

     - parameter centeredId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter text: (query)  (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func centeredtextDeleteWithRequestBuilder(centeredId: String? = nil, scriptId: String? = nil, text: String? = nil, prefer: Prefer_centeredtextDelete? = nil) -> RequestBuilder<Void> {
        let path = "/centeredtext"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "centered_id": centeredId, 
                        "script_id": scriptId, 
                        "text": text
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_centeredtextGet: String { 
        case count&#x3D;none = "count=none"
    }

    /**

     - parameter centeredId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter text: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func centeredtextGet(centeredId: String? = nil, scriptId: String? = nil, text: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_centeredtextGet? = nil, completion: @escaping ((_ data: [Centeredtext]?,_ error: Error?) -> Void)) {
        centeredtextGetWithRequestBuilder(centeredId: centeredId, scriptId: scriptId, text: text, select: select, order: order, range: range, rangeUnit: rangeUnit, offset: offset, limit: limit, prefer: prefer).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /centeredtext
     - 

     - examples: [{contentType=application/json, example=[ {
  "centered_id" : 0,
  "script_id" : 6,
  "text" : "text"
}, {
  "centered_id" : 0,
  "script_id" : 6,
  "text" : "text"
} ]}]
     - parameter centeredId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter text: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<[Centeredtext]> 
     */
    open class func centeredtextGetWithRequestBuilder(centeredId: String? = nil, scriptId: String? = nil, text: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_centeredtextGet? = nil) -> RequestBuilder<[Centeredtext]> {
        let path = "/centeredtext"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "centered_id": centeredId, 
                        "script_id": scriptId, 
                        "text": text, 
                        "select": select, 
                        "order": order, 
                        "offset": offset, 
                        "limit": limit
        ])
        let nillableHeaders: [String: Any?] = [
                        "Range": range,
                        "Range-Unit": rangeUnit,
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[Centeredtext]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_centeredtextPatch: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter body: (body) centeredtext (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter centeredId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter text: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func centeredtextPatch(body: Centeredtext? = nil, prefer: Prefer_centeredtextPatch? = nil, centeredId: String? = nil, scriptId: String? = nil, text: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        centeredtextPatchWithRequestBuilder(body: body, prefer: prefer, centeredId: centeredId, scriptId: scriptId, text: text).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - PATCH /centeredtext
     - 

     - parameter body: (body) centeredtext (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter centeredId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter text: (query)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func centeredtextPatchWithRequestBuilder(body: Centeredtext? = nil, prefer: Prefer_centeredtextPatch? = nil, centeredId: String? = nil, scriptId: String? = nil, text: String? = nil) -> RequestBuilder<Void> {
        let path = "/centeredtext"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "centered_id": centeredId, 
                        "script_id": scriptId, 
                        "text": text
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_centeredtextPost: String { 
        case return&#x3D;representation = "return=representation"
        case return&#x3D;minimal = "return=minimal"
        case return&#x3D;none = "return=none"
        case resolution&#x3D;ignoreDuplicates = "resolution=ignore-duplicates"
        case resolution&#x3D;mergeDuplicates = "resolution=merge-duplicates"
    }

    /**

     - parameter body: (body) centeredtext (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func centeredtextPost(body: Centeredtext? = nil, prefer: Prefer_centeredtextPost? = nil, select: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        centeredtextPostWithRequestBuilder(body: body, prefer: prefer, select: select).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - POST /centeredtext
     - 

     - parameter body: (body) centeredtext (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func centeredtextPostWithRequestBuilder(body: Centeredtext? = nil, prefer: Prefer_centeredtextPost? = nil, select: String? = nil) -> RequestBuilder<Void> {
        let path = "/centeredtext"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "select": select
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
}
