//
// CharacterAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class CharacterAPI {
    /**
     * enum for parameter prefer
     */
    public enum Prefer_characterDelete: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter characterId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter name: (query)  (optional)
     - parameter _description: (query)  (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func characterDelete(characterId: String? = nil, scriptId: String? = nil, name: String? = nil, _description: String? = nil, prefer: Prefer_characterDelete? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        characterDeleteWithRequestBuilder(characterId: characterId, scriptId: scriptId, name: name, _description: _description, prefer: prefer).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /character
     - 

     - parameter characterId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter name: (query)  (optional)
     - parameter _description: (query)  (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func characterDeleteWithRequestBuilder(characterId: String? = nil, scriptId: String? = nil, name: String? = nil, _description: String? = nil, prefer: Prefer_characterDelete? = nil) -> RequestBuilder<Void> {
        let path = "/character"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "character_id": characterId, 
                        "script_id": scriptId, 
                        "name": name, 
                        "description": _description
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_characterGet: String { 
        case count&#x3D;none = "count=none"
    }

    /**

     - parameter characterId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter name: (query)  (optional)
     - parameter _description: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func characterGet(characterId: String? = nil, scriptId: String? = nil, name: String? = nil, _description: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_characterGet? = nil, completion: @escaping ((_ data: [ModelCharacter]?,_ error: Error?) -> Void)) {
        characterGetWithRequestBuilder(characterId: characterId, scriptId: scriptId, name: name, _description: _description, select: select, order: order, range: range, rangeUnit: rangeUnit, offset: offset, limit: limit, prefer: prefer).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /character
     - 

     - examples: [{contentType=application/json, example=[ {
  "name" : "name",
  "description" : "description",
  "script_id" : 6,
  "character_id" : 0
}, {
  "name" : "name",
  "description" : "description",
  "script_id" : 6,
  "character_id" : 0
} ]}]
     - parameter characterId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter name: (query)  (optional)
     - parameter _description: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<[ModelCharacter]> 
     */
    open class func characterGetWithRequestBuilder(characterId: String? = nil, scriptId: String? = nil, name: String? = nil, _description: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_characterGet? = nil) -> RequestBuilder<[ModelCharacter]> {
        let path = "/character"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "character_id": characterId, 
                        "script_id": scriptId, 
                        "name": name, 
                        "description": _description, 
                        "select": select, 
                        "order": order, 
                        "offset": offset, 
                        "limit": limit
        ])
        let nillableHeaders: [String: Any?] = [
                        "Range": range,
                        "Range-Unit": rangeUnit,
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[ModelCharacter]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_characterPatch: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter body: (body) character (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter characterId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter name: (query)  (optional)
     - parameter _description: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func characterPatch(body: ModelCharacter? = nil, prefer: Prefer_characterPatch? = nil, characterId: String? = nil, scriptId: String? = nil, name: String? = nil, _description: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        characterPatchWithRequestBuilder(body: body, prefer: prefer, characterId: characterId, scriptId: scriptId, name: name, _description: _description).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - PATCH /character
     - 

     - parameter body: (body) character (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter characterId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter name: (query)  (optional)
     - parameter _description: (query)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func characterPatchWithRequestBuilder(body: ModelCharacter? = nil, prefer: Prefer_characterPatch? = nil, characterId: String? = nil, scriptId: String? = nil, name: String? = nil, _description: String? = nil) -> RequestBuilder<Void> {
        let path = "/character"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "character_id": characterId, 
                        "script_id": scriptId, 
                        "name": name, 
                        "description": _description
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_characterPost: String { 
        case return&#x3D;representation = "return=representation"
        case return&#x3D;minimal = "return=minimal"
        case return&#x3D;none = "return=none"
        case resolution&#x3D;ignoreDuplicates = "resolution=ignore-duplicates"
        case resolution&#x3D;mergeDuplicates = "resolution=merge-duplicates"
    }

    /**

     - parameter body: (body) character (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func characterPost(body: ModelCharacter? = nil, prefer: Prefer_characterPost? = nil, select: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        characterPostWithRequestBuilder(body: body, prefer: prefer, select: select).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - POST /character
     - 

     - parameter body: (body) character (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func characterPostWithRequestBuilder(body: ModelCharacter? = nil, prefer: Prefer_characterPost? = nil, select: String? = nil) -> RequestBuilder<Void> {
        let path = "/character"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "select": select
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
}
