//
// DialogueAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class DialogueAPI {
    /**
     * enum for parameter prefer
     */
    public enum Prefer_dialogueDelete: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter dialogueId: (query)  (optional)
     - parameter sceneId: (query)  (optional)
     - parameter characterId: (query)  (optional)
     - parameter originalText: (query)  (optional)
     - parameter modernizedText: (query)  (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func dialogueDelete(dialogueId: String? = nil, sceneId: String? = nil, characterId: String? = nil, originalText: String? = nil, modernizedText: String? = nil, prefer: Prefer_dialogueDelete? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        dialogueDeleteWithRequestBuilder(dialogueId: dialogueId, sceneId: sceneId, characterId: characterId, originalText: originalText, modernizedText: modernizedText, prefer: prefer).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /dialogue
     - 

     - parameter dialogueId: (query)  (optional)
     - parameter sceneId: (query)  (optional)
     - parameter characterId: (query)  (optional)
     - parameter originalText: (query)  (optional)
     - parameter modernizedText: (query)  (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func dialogueDeleteWithRequestBuilder(dialogueId: String? = nil, sceneId: String? = nil, characterId: String? = nil, originalText: String? = nil, modernizedText: String? = nil, prefer: Prefer_dialogueDelete? = nil) -> RequestBuilder<Void> {
        let path = "/dialogue"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "dialogue_id": dialogueId, 
                        "scene_id": sceneId, 
                        "character_id": characterId, 
                        "original_text": originalText, 
                        "modernized_text": modernizedText
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_dialogueGet: String { 
        case count&#x3D;none = "count=none"
    }

    /**

     - parameter dialogueId: (query)  (optional)
     - parameter sceneId: (query)  (optional)
     - parameter characterId: (query)  (optional)
     - parameter originalText: (query)  (optional)
     - parameter modernizedText: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func dialogueGet(dialogueId: String? = nil, sceneId: String? = nil, characterId: String? = nil, originalText: String? = nil, modernizedText: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_dialogueGet? = nil, completion: @escaping ((_ data: [Dialogue]?,_ error: Error?) -> Void)) {
        dialogueGetWithRequestBuilder(dialogueId: dialogueId, sceneId: sceneId, characterId: characterId, originalText: originalText, modernizedText: modernizedText, select: select, order: order, range: range, rangeUnit: rangeUnit, offset: offset, limit: limit, prefer: prefer).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /dialogue
     - 

     - examples: [{contentType=application/json, example=[ {
  "modernized_text" : "modernized_text",
  "scene_id" : 6,
  "dialogue_id" : 0,
  "character_id" : 1,
  "original_text" : "original_text"
}, {
  "modernized_text" : "modernized_text",
  "scene_id" : 6,
  "dialogue_id" : 0,
  "character_id" : 1,
  "original_text" : "original_text"
} ]}]
     - parameter dialogueId: (query)  (optional)
     - parameter sceneId: (query)  (optional)
     - parameter characterId: (query)  (optional)
     - parameter originalText: (query)  (optional)
     - parameter modernizedText: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<[Dialogue]> 
     */
    open class func dialogueGetWithRequestBuilder(dialogueId: String? = nil, sceneId: String? = nil, characterId: String? = nil, originalText: String? = nil, modernizedText: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_dialogueGet? = nil) -> RequestBuilder<[Dialogue]> {
        let path = "/dialogue"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "dialogue_id": dialogueId, 
                        "scene_id": sceneId, 
                        "character_id": characterId, 
                        "original_text": originalText, 
                        "modernized_text": modernizedText, 
                        "select": select, 
                        "order": order, 
                        "offset": offset, 
                        "limit": limit
        ])
        let nillableHeaders: [String: Any?] = [
                        "Range": range,
                        "Range-Unit": rangeUnit,
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[Dialogue]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_dialoguePatch: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter body: (body) dialogue (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter dialogueId: (query)  (optional)
     - parameter sceneId: (query)  (optional)
     - parameter characterId: (query)  (optional)
     - parameter originalText: (query)  (optional)
     - parameter modernizedText: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func dialoguePatch(body: Dialogue? = nil, prefer: Prefer_dialoguePatch? = nil, dialogueId: String? = nil, sceneId: String? = nil, characterId: String? = nil, originalText: String? = nil, modernizedText: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        dialoguePatchWithRequestBuilder(body: body, prefer: prefer, dialogueId: dialogueId, sceneId: sceneId, characterId: characterId, originalText: originalText, modernizedText: modernizedText).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - PATCH /dialogue
     - 

     - parameter body: (body) dialogue (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter dialogueId: (query)  (optional)
     - parameter sceneId: (query)  (optional)
     - parameter characterId: (query)  (optional)
     - parameter originalText: (query)  (optional)
     - parameter modernizedText: (query)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func dialoguePatchWithRequestBuilder(body: Dialogue? = nil, prefer: Prefer_dialoguePatch? = nil, dialogueId: String? = nil, sceneId: String? = nil, characterId: String? = nil, originalText: String? = nil, modernizedText: String? = nil) -> RequestBuilder<Void> {
        let path = "/dialogue"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "dialogue_id": dialogueId, 
                        "scene_id": sceneId, 
                        "character_id": characterId, 
                        "original_text": originalText, 
                        "modernized_text": modernizedText
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_dialoguePost: String { 
        case return&#x3D;representation = "return=representation"
        case return&#x3D;minimal = "return=minimal"
        case return&#x3D;none = "return=none"
        case resolution&#x3D;ignoreDuplicates = "resolution=ignore-duplicates"
        case resolution&#x3D;mergeDuplicates = "resolution=merge-duplicates"
    }

    /**

     - parameter body: (body) dialogue (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func dialoguePost(body: Dialogue? = nil, prefer: Prefer_dialoguePost? = nil, select: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        dialoguePostWithRequestBuilder(body: body, prefer: prefer, select: select).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - POST /dialogue
     - 

     - parameter body: (body) dialogue (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func dialoguePostWithRequestBuilder(body: Dialogue? = nil, prefer: Prefer_dialoguePost? = nil, select: String? = nil) -> RequestBuilder<Void> {
        let path = "/dialogue"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "select": select
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
}
