//
// ExtendednotesresearchAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class ExtendednotesresearchAPI {
    /**
     * enum for parameter prefer
     */
    public enum Prefer_extendednotesresearchDelete: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter researchId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter notes: (query)  (optional)
     - parameter researchDetails: (query)  (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func extendednotesresearchDelete(researchId: String? = nil, scriptId: String? = nil, notes: String? = nil, researchDetails: String? = nil, prefer: Prefer_extendednotesresearchDelete? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        extendednotesresearchDeleteWithRequestBuilder(researchId: researchId, scriptId: scriptId, notes: notes, researchDetails: researchDetails, prefer: prefer).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /extendednotesresearch
     - 

     - parameter researchId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter notes: (query)  (optional)
     - parameter researchDetails: (query)  (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func extendednotesresearchDeleteWithRequestBuilder(researchId: String? = nil, scriptId: String? = nil, notes: String? = nil, researchDetails: String? = nil, prefer: Prefer_extendednotesresearchDelete? = nil) -> RequestBuilder<Void> {
        let path = "/extendednotesresearch"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "research_id": researchId, 
                        "script_id": scriptId, 
                        "notes": notes, 
                        "research_details": researchDetails
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_extendednotesresearchGet: String { 
        case count&#x3D;none = "count=none"
    }

    /**

     - parameter researchId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter notes: (query)  (optional)
     - parameter researchDetails: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func extendednotesresearchGet(researchId: String? = nil, scriptId: String? = nil, notes: String? = nil, researchDetails: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_extendednotesresearchGet? = nil, completion: @escaping ((_ data: [Extendednotesresearch]?,_ error: Error?) -> Void)) {
        extendednotesresearchGetWithRequestBuilder(researchId: researchId, scriptId: scriptId, notes: notes, researchDetails: researchDetails, select: select, order: order, range: range, rangeUnit: rangeUnit, offset: offset, limit: limit, prefer: prefer).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /extendednotesresearch
     - 

     - examples: [{contentType=application/json, example=[ {
  "research_id" : 0,
  "research_details" : "research_details",
  "notes" : "notes",
  "script_id" : 6
}, {
  "research_id" : 0,
  "research_details" : "research_details",
  "notes" : "notes",
  "script_id" : 6
} ]}]
     - parameter researchId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter notes: (query)  (optional)
     - parameter researchDetails: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<[Extendednotesresearch]> 
     */
    open class func extendednotesresearchGetWithRequestBuilder(researchId: String? = nil, scriptId: String? = nil, notes: String? = nil, researchDetails: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_extendednotesresearchGet? = nil) -> RequestBuilder<[Extendednotesresearch]> {
        let path = "/extendednotesresearch"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "research_id": researchId, 
                        "script_id": scriptId, 
                        "notes": notes, 
                        "research_details": researchDetails, 
                        "select": select, 
                        "order": order, 
                        "offset": offset, 
                        "limit": limit
        ])
        let nillableHeaders: [String: Any?] = [
                        "Range": range,
                        "Range-Unit": rangeUnit,
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[Extendednotesresearch]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_extendednotesresearchPatch: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter body: (body) extendednotesresearch (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter researchId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter notes: (query)  (optional)
     - parameter researchDetails: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func extendednotesresearchPatch(body: Extendednotesresearch? = nil, prefer: Prefer_extendednotesresearchPatch? = nil, researchId: String? = nil, scriptId: String? = nil, notes: String? = nil, researchDetails: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        extendednotesresearchPatchWithRequestBuilder(body: body, prefer: prefer, researchId: researchId, scriptId: scriptId, notes: notes, researchDetails: researchDetails).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - PATCH /extendednotesresearch
     - 

     - parameter body: (body) extendednotesresearch (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter researchId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter notes: (query)  (optional)
     - parameter researchDetails: (query)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func extendednotesresearchPatchWithRequestBuilder(body: Extendednotesresearch? = nil, prefer: Prefer_extendednotesresearchPatch? = nil, researchId: String? = nil, scriptId: String? = nil, notes: String? = nil, researchDetails: String? = nil) -> RequestBuilder<Void> {
        let path = "/extendednotesresearch"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "research_id": researchId, 
                        "script_id": scriptId, 
                        "notes": notes, 
                        "research_details": researchDetails
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_extendednotesresearchPost: String { 
        case return&#x3D;representation = "return=representation"
        case return&#x3D;minimal = "return=minimal"
        case return&#x3D;none = "return=none"
        case resolution&#x3D;ignoreDuplicates = "resolution=ignore-duplicates"
        case resolution&#x3D;mergeDuplicates = "resolution=merge-duplicates"
    }

    /**

     - parameter body: (body) extendednotesresearch (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func extendednotesresearchPost(body: Extendednotesresearch? = nil, prefer: Prefer_extendednotesresearchPost? = nil, select: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        extendednotesresearchPostWithRequestBuilder(body: body, prefer: prefer, select: select).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - POST /extendednotesresearch
     - 

     - parameter body: (body) extendednotesresearch (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func extendednotesresearchPostWithRequestBuilder(body: Extendednotesresearch? = nil, prefer: Prefer_extendednotesresearchPost? = nil, select: String? = nil) -> RequestBuilder<Void> {
        let path = "/extendednotesresearch"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "select": select
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
}
