//
// FormattingrulesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class FormattingrulesAPI {
    /**
     * enum for parameter prefer
     */
    public enum Prefer_formattingrulesDelete: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter ruleId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter ruleDescription: (query)  (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func formattingrulesDelete(ruleId: String? = nil, scriptId: String? = nil, ruleDescription: String? = nil, prefer: Prefer_formattingrulesDelete? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        formattingrulesDeleteWithRequestBuilder(ruleId: ruleId, scriptId: scriptId, ruleDescription: ruleDescription, prefer: prefer).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /formattingrules
     - 

     - parameter ruleId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter ruleDescription: (query)  (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func formattingrulesDeleteWithRequestBuilder(ruleId: String? = nil, scriptId: String? = nil, ruleDescription: String? = nil, prefer: Prefer_formattingrulesDelete? = nil) -> RequestBuilder<Void> {
        let path = "/formattingrules"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "rule_id": ruleId, 
                        "script_id": scriptId, 
                        "rule_description": ruleDescription
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_formattingrulesGet: String { 
        case count&#x3D;none = "count=none"
    }

    /**

     - parameter ruleId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter ruleDescription: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func formattingrulesGet(ruleId: String? = nil, scriptId: String? = nil, ruleDescription: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_formattingrulesGet? = nil, completion: @escaping ((_ data: [Formattingrules]?,_ error: Error?) -> Void)) {
        formattingrulesGetWithRequestBuilder(ruleId: ruleId, scriptId: scriptId, ruleDescription: ruleDescription, select: select, order: order, range: range, rangeUnit: rangeUnit, offset: offset, limit: limit, prefer: prefer).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /formattingrules
     - 

     - examples: [{contentType=application/json, example=[ {
  "rule_id" : 0,
  "rule_description" : "rule_description",
  "script_id" : 6
}, {
  "rule_id" : 0,
  "rule_description" : "rule_description",
  "script_id" : 6
} ]}]
     - parameter ruleId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter ruleDescription: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<[Formattingrules]> 
     */
    open class func formattingrulesGetWithRequestBuilder(ruleId: String? = nil, scriptId: String? = nil, ruleDescription: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_formattingrulesGet? = nil) -> RequestBuilder<[Formattingrules]> {
        let path = "/formattingrules"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "rule_id": ruleId, 
                        "script_id": scriptId, 
                        "rule_description": ruleDescription, 
                        "select": select, 
                        "order": order, 
                        "offset": offset, 
                        "limit": limit
        ])
        let nillableHeaders: [String: Any?] = [
                        "Range": range,
                        "Range-Unit": rangeUnit,
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[Formattingrules]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_formattingrulesPatch: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter body: (body) formattingrules (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter ruleId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter ruleDescription: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func formattingrulesPatch(body: Formattingrules? = nil, prefer: Prefer_formattingrulesPatch? = nil, ruleId: String? = nil, scriptId: String? = nil, ruleDescription: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        formattingrulesPatchWithRequestBuilder(body: body, prefer: prefer, ruleId: ruleId, scriptId: scriptId, ruleDescription: ruleDescription).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - PATCH /formattingrules
     - 

     - parameter body: (body) formattingrules (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter ruleId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter ruleDescription: (query)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func formattingrulesPatchWithRequestBuilder(body: Formattingrules? = nil, prefer: Prefer_formattingrulesPatch? = nil, ruleId: String? = nil, scriptId: String? = nil, ruleDescription: String? = nil) -> RequestBuilder<Void> {
        let path = "/formattingrules"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "rule_id": ruleId, 
                        "script_id": scriptId, 
                        "rule_description": ruleDescription
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_formattingrulesPost: String { 
        case return&#x3D;representation = "return=representation"
        case return&#x3D;minimal = "return=minimal"
        case return&#x3D;none = "return=none"
        case resolution&#x3D;ignoreDuplicates = "resolution=ignore-duplicates"
        case resolution&#x3D;mergeDuplicates = "resolution=merge-duplicates"
    }

    /**

     - parameter body: (body) formattingrules (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func formattingrulesPost(body: Formattingrules? = nil, prefer: Prefer_formattingrulesPost? = nil, select: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        formattingrulesPostWithRequestBuilder(body: body, prefer: prefer, select: select).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - POST /formattingrules
     - 

     - parameter body: (body) formattingrules (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func formattingrulesPostWithRequestBuilder(body: Formattingrules? = nil, prefer: Prefer_formattingrulesPost? = nil, select: String? = nil) -> RequestBuilder<Void> {
        let path = "/formattingrules"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "select": select
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
}
