//
// MetadataAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class MetadataAPI {
    /**
     * enum for parameter prefer
     */
    public enum Prefer_metadataDelete: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter metadataId: (query)  (optional)
     - parameter creationDate: (query)  (optional)
     - parameter lastModifiedDate: (query)  (optional)
     - parameter versionNumber: (query)  (optional)
     - parameter additionalInformation: (query)  (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func metadataDelete(metadataId: String? = nil, creationDate: Date? = nil, lastModifiedDate: Date? = nil, versionNumber: String? = nil, additionalInformation: String? = nil, prefer: Prefer_metadataDelete? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        metadataDeleteWithRequestBuilder(metadataId: metadataId, creationDate: creationDate, lastModifiedDate: lastModifiedDate, versionNumber: versionNumber, additionalInformation: additionalInformation, prefer: prefer).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /metadata
     - 

     - parameter metadataId: (query)  (optional)
     - parameter creationDate: (query)  (optional)
     - parameter lastModifiedDate: (query)  (optional)
     - parameter versionNumber: (query)  (optional)
     - parameter additionalInformation: (query)  (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func metadataDeleteWithRequestBuilder(metadataId: String? = nil, creationDate: Date? = nil, lastModifiedDate: Date? = nil, versionNumber: String? = nil, additionalInformation: String? = nil, prefer: Prefer_metadataDelete? = nil) -> RequestBuilder<Void> {
        let path = "/metadata"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "metadata_id": metadataId, 
                        "creation_date": creationDate?.encodeToJSON(), 
                        "last_modified_date": lastModifiedDate?.encodeToJSON(), 
                        "version_number": versionNumber, 
                        "additional_information": additionalInformation
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_metadataGet: String { 
        case count&#x3D;none = "count=none"
    }

    /**

     - parameter metadataId: (query)  (optional)
     - parameter creationDate: (query)  (optional)
     - parameter lastModifiedDate: (query)  (optional)
     - parameter versionNumber: (query)  (optional)
     - parameter additionalInformation: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func metadataGet(metadataId: String? = nil, creationDate: Date? = nil, lastModifiedDate: Date? = nil, versionNumber: String? = nil, additionalInformation: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_metadataGet? = nil, completion: @escaping ((_ data: [Metadata]?,_ error: Error?) -> Void)) {
        metadataGetWithRequestBuilder(metadataId: metadataId, creationDate: creationDate, lastModifiedDate: lastModifiedDate, versionNumber: versionNumber, additionalInformation: additionalInformation, select: select, order: order, range: range, rangeUnit: rangeUnit, offset: offset, limit: limit, prefer: prefer).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /metadata
     - 

     - examples: [{contentType=application/json, example=[ {
  "additional_information" : "additional_information",
  "metadata_id" : 0,
  "last_modified_date" : "2000-01-23",
  "version_number" : 6,
  "creation_date" : "2000-01-23"
}, {
  "additional_information" : "additional_information",
  "metadata_id" : 0,
  "last_modified_date" : "2000-01-23",
  "version_number" : 6,
  "creation_date" : "2000-01-23"
} ]}]
     - parameter metadataId: (query)  (optional)
     - parameter creationDate: (query)  (optional)
     - parameter lastModifiedDate: (query)  (optional)
     - parameter versionNumber: (query)  (optional)
     - parameter additionalInformation: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<[Metadata]> 
     */
    open class func metadataGetWithRequestBuilder(metadataId: String? = nil, creationDate: Date? = nil, lastModifiedDate: Date? = nil, versionNumber: String? = nil, additionalInformation: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_metadataGet? = nil) -> RequestBuilder<[Metadata]> {
        let path = "/metadata"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "metadata_id": metadataId, 
                        "creation_date": creationDate?.encodeToJSON(), 
                        "last_modified_date": lastModifiedDate?.encodeToJSON(), 
                        "version_number": versionNumber, 
                        "additional_information": additionalInformation, 
                        "select": select, 
                        "order": order, 
                        "offset": offset, 
                        "limit": limit
        ])
        let nillableHeaders: [String: Any?] = [
                        "Range": range,
                        "Range-Unit": rangeUnit,
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[Metadata]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_metadataPatch: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter body: (body) metadata (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter metadataId: (query)  (optional)
     - parameter creationDate: (query)  (optional)
     - parameter lastModifiedDate: (query)  (optional)
     - parameter versionNumber: (query)  (optional)
     - parameter additionalInformation: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func metadataPatch(body: Metadata? = nil, prefer: Prefer_metadataPatch? = nil, metadataId: String? = nil, creationDate: Date? = nil, lastModifiedDate: Date? = nil, versionNumber: String? = nil, additionalInformation: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        metadataPatchWithRequestBuilder(body: body, prefer: prefer, metadataId: metadataId, creationDate: creationDate, lastModifiedDate: lastModifiedDate, versionNumber: versionNumber, additionalInformation: additionalInformation).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - PATCH /metadata
     - 

     - parameter body: (body) metadata (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter metadataId: (query)  (optional)
     - parameter creationDate: (query)  (optional)
     - parameter lastModifiedDate: (query)  (optional)
     - parameter versionNumber: (query)  (optional)
     - parameter additionalInformation: (query)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func metadataPatchWithRequestBuilder(body: Metadata? = nil, prefer: Prefer_metadataPatch? = nil, metadataId: String? = nil, creationDate: Date? = nil, lastModifiedDate: Date? = nil, versionNumber: String? = nil, additionalInformation: String? = nil) -> RequestBuilder<Void> {
        let path = "/metadata"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "metadata_id": metadataId, 
                        "creation_date": creationDate?.encodeToJSON(), 
                        "last_modified_date": lastModifiedDate?.encodeToJSON(), 
                        "version_number": versionNumber, 
                        "additional_information": additionalInformation
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_metadataPost: String { 
        case return&#x3D;representation = "return=representation"
        case return&#x3D;minimal = "return=minimal"
        case return&#x3D;none = "return=none"
        case resolution&#x3D;ignoreDuplicates = "resolution=ignore-duplicates"
        case resolution&#x3D;mergeDuplicates = "resolution=merge-duplicates"
    }

    /**

     - parameter body: (body) metadata (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func metadataPost(body: Metadata? = nil, prefer: Prefer_metadataPost? = nil, select: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        metadataPostWithRequestBuilder(body: body, prefer: prefer, select: select).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - POST /metadata
     - 

     - parameter body: (body) metadata (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func metadataPostWithRequestBuilder(body: Metadata? = nil, prefer: Prefer_metadataPost? = nil, select: String? = nil) -> RequestBuilder<Void> {
        let path = "/metadata"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "select": select
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
}
