//
// PlaywrightAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class PlaywrightAPI {
    /**
     * enum for parameter prefer
     */
    public enum Prefer_playwrightDelete: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter authorId: (query)  (optional)
     - parameter name: (query)  (optional)
     - parameter biography: (query)  (optional)
     - parameter contactInformation: (query)  (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func playwrightDelete(authorId: String? = nil, name: String? = nil, biography: String? = nil, contactInformation: String? = nil, prefer: Prefer_playwrightDelete? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        playwrightDeleteWithRequestBuilder(authorId: authorId, name: name, biography: biography, contactInformation: contactInformation, prefer: prefer).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /playwright
     - 

     - parameter authorId: (query)  (optional)
     - parameter name: (query)  (optional)
     - parameter biography: (query)  (optional)
     - parameter contactInformation: (query)  (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func playwrightDeleteWithRequestBuilder(authorId: String? = nil, name: String? = nil, biography: String? = nil, contactInformation: String? = nil, prefer: Prefer_playwrightDelete? = nil) -> RequestBuilder<Void> {
        let path = "/playwright"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "author_id": authorId, 
                        "name": name, 
                        "biography": biography, 
                        "contact_information": contactInformation
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_playwrightGet: String { 
        case count&#x3D;none = "count=none"
    }

    /**

     - parameter authorId: (query)  (optional)
     - parameter name: (query)  (optional)
     - parameter biography: (query)  (optional)
     - parameter contactInformation: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func playwrightGet(authorId: String? = nil, name: String? = nil, biography: String? = nil, contactInformation: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_playwrightGet? = nil, completion: @escaping ((_ data: [Playwright]?,_ error: Error?) -> Void)) {
        playwrightGetWithRequestBuilder(authorId: authorId, name: name, biography: biography, contactInformation: contactInformation, select: select, order: order, range: range, rangeUnit: rangeUnit, offset: offset, limit: limit, prefer: prefer).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /playwright
     - 

     - examples: [{contentType=application/json, example=[ {
  "name" : "name",
  "contact_information" : "contact_information",
  "biography" : "biography",
  "author_id" : 0
}, {
  "name" : "name",
  "contact_information" : "contact_information",
  "biography" : "biography",
  "author_id" : 0
} ]}]
     - parameter authorId: (query)  (optional)
     - parameter name: (query)  (optional)
     - parameter biography: (query)  (optional)
     - parameter contactInformation: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<[Playwright]> 
     */
    open class func playwrightGetWithRequestBuilder(authorId: String? = nil, name: String? = nil, biography: String? = nil, contactInformation: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_playwrightGet? = nil) -> RequestBuilder<[Playwright]> {
        let path = "/playwright"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "author_id": authorId, 
                        "name": name, 
                        "biography": biography, 
                        "contact_information": contactInformation, 
                        "select": select, 
                        "order": order, 
                        "offset": offset, 
                        "limit": limit
        ])
        let nillableHeaders: [String: Any?] = [
                        "Range": range,
                        "Range-Unit": rangeUnit,
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[Playwright]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_playwrightPatch: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter body: (body) playwright (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter authorId: (query)  (optional)
     - parameter name: (query)  (optional)
     - parameter biography: (query)  (optional)
     - parameter contactInformation: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func playwrightPatch(body: Playwright? = nil, prefer: Prefer_playwrightPatch? = nil, authorId: String? = nil, name: String? = nil, biography: String? = nil, contactInformation: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        playwrightPatchWithRequestBuilder(body: body, prefer: prefer, authorId: authorId, name: name, biography: biography, contactInformation: contactInformation).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - PATCH /playwright
     - 

     - parameter body: (body) playwright (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter authorId: (query)  (optional)
     - parameter name: (query)  (optional)
     - parameter biography: (query)  (optional)
     - parameter contactInformation: (query)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func playwrightPatchWithRequestBuilder(body: Playwright? = nil, prefer: Prefer_playwrightPatch? = nil, authorId: String? = nil, name: String? = nil, biography: String? = nil, contactInformation: String? = nil) -> RequestBuilder<Void> {
        let path = "/playwright"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "author_id": authorId, 
                        "name": name, 
                        "biography": biography, 
                        "contact_information": contactInformation
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_playwrightPost: String { 
        case return&#x3D;representation = "return=representation"
        case return&#x3D;minimal = "return=minimal"
        case return&#x3D;none = "return=none"
        case resolution&#x3D;ignoreDuplicates = "resolution=ignore-duplicates"
        case resolution&#x3D;mergeDuplicates = "resolution=merge-duplicates"
    }

    /**

     - parameter body: (body) playwright (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func playwrightPost(body: Playwright? = nil, prefer: Prefer_playwrightPost? = nil, select: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        playwrightPostWithRequestBuilder(body: body, prefer: prefer, select: select).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - POST /playwright
     - 

     - parameter body: (body) playwright (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func playwrightPostWithRequestBuilder(body: Playwright? = nil, prefer: Prefer_playwrightPost? = nil, select: String? = nil) -> RequestBuilder<Void> {
        let path = "/playwright"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "select": select
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
}
