//
// PropsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class PropsAPI {
    /**
     * enum for parameter prefer
     */
    public enum Prefer_propsDelete: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter propId: (query)  (optional)
     - parameter sceneId: (query)  (optional)
     - parameter _description: (query)  (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func propsDelete(propId: String? = nil, sceneId: String? = nil, _description: String? = nil, prefer: Prefer_propsDelete? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        propsDeleteWithRequestBuilder(propId: propId, sceneId: sceneId, _description: _description, prefer: prefer).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /props
     - 

     - parameter propId: (query)  (optional)
     - parameter sceneId: (query)  (optional)
     - parameter _description: (query)  (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func propsDeleteWithRequestBuilder(propId: String? = nil, sceneId: String? = nil, _description: String? = nil, prefer: Prefer_propsDelete? = nil) -> RequestBuilder<Void> {
        let path = "/props"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "prop_id": propId, 
                        "scene_id": sceneId, 
                        "description": _description
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_propsGet: String { 
        case count&#x3D;none = "count=none"
    }

    /**

     - parameter propId: (query)  (optional)
     - parameter sceneId: (query)  (optional)
     - parameter _description: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func propsGet(propId: String? = nil, sceneId: String? = nil, _description: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_propsGet? = nil, completion: @escaping ((_ data: [Props]?,_ error: Error?) -> Void)) {
        propsGetWithRequestBuilder(propId: propId, sceneId: sceneId, _description: _description, select: select, order: order, range: range, rangeUnit: rangeUnit, offset: offset, limit: limit, prefer: prefer).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /props
     - 

     - examples: [{contentType=application/json, example=[ {
  "prop_id" : 0,
  "scene_id" : 6,
  "description" : "description"
}, {
  "prop_id" : 0,
  "scene_id" : 6,
  "description" : "description"
} ]}]
     - parameter propId: (query)  (optional)
     - parameter sceneId: (query)  (optional)
     - parameter _description: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<[Props]> 
     */
    open class func propsGetWithRequestBuilder(propId: String? = nil, sceneId: String? = nil, _description: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_propsGet? = nil) -> RequestBuilder<[Props]> {
        let path = "/props"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "prop_id": propId, 
                        "scene_id": sceneId, 
                        "description": _description, 
                        "select": select, 
                        "order": order, 
                        "offset": offset, 
                        "limit": limit
        ])
        let nillableHeaders: [String: Any?] = [
                        "Range": range,
                        "Range-Unit": rangeUnit,
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[Props]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_propsPatch: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter body: (body) props (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter propId: (query)  (optional)
     - parameter sceneId: (query)  (optional)
     - parameter _description: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func propsPatch(body: Props? = nil, prefer: Prefer_propsPatch? = nil, propId: String? = nil, sceneId: String? = nil, _description: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        propsPatchWithRequestBuilder(body: body, prefer: prefer, propId: propId, sceneId: sceneId, _description: _description).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - PATCH /props
     - 

     - parameter body: (body) props (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter propId: (query)  (optional)
     - parameter sceneId: (query)  (optional)
     - parameter _description: (query)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func propsPatchWithRequestBuilder(body: Props? = nil, prefer: Prefer_propsPatch? = nil, propId: String? = nil, sceneId: String? = nil, _description: String? = nil) -> RequestBuilder<Void> {
        let path = "/props"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "prop_id": propId, 
                        "scene_id": sceneId, 
                        "description": _description
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_propsPost: String { 
        case return&#x3D;representation = "return=representation"
        case return&#x3D;minimal = "return=minimal"
        case return&#x3D;none = "return=none"
        case resolution&#x3D;ignoreDuplicates = "resolution=ignore-duplicates"
        case resolution&#x3D;mergeDuplicates = "resolution=merge-duplicates"
    }

    /**

     - parameter body: (body) props (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func propsPost(body: Props? = nil, prefer: Prefer_propsPost? = nil, select: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        propsPostWithRequestBuilder(body: body, prefer: prefer, select: select).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - POST /props
     - 

     - parameter body: (body) props (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func propsPostWithRequestBuilder(body: Props? = nil, prefer: Prefer_propsPost? = nil, select: String? = nil) -> RequestBuilder<Void> {
        let path = "/props"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "select": select
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
}
