//
// RevisionhistoryAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class RevisionhistoryAPI {
    /**
     * enum for parameter prefer
     */
    public enum Prefer_revisionhistoryDelete: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter revisionId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter date: (query)  (optional)
     - parameter changeDescription: (query)  (optional)
     - parameter editor: (query)  (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func revisionhistoryDelete(revisionId: String? = nil, scriptId: String? = nil, date: Date? = nil, changeDescription: String? = nil, editor: String? = nil, prefer: Prefer_revisionhistoryDelete? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        revisionhistoryDeleteWithRequestBuilder(revisionId: revisionId, scriptId: scriptId, date: date, changeDescription: changeDescription, editor: editor, prefer: prefer).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /revisionhistory
     - 

     - parameter revisionId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter date: (query)  (optional)
     - parameter changeDescription: (query)  (optional)
     - parameter editor: (query)  (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func revisionhistoryDeleteWithRequestBuilder(revisionId: String? = nil, scriptId: String? = nil, date: Date? = nil, changeDescription: String? = nil, editor: String? = nil, prefer: Prefer_revisionhistoryDelete? = nil) -> RequestBuilder<Void> {
        let path = "/revisionhistory"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "revision_id": revisionId, 
                        "script_id": scriptId, 
                        "date": date?.encodeToJSON(), 
                        "change_description": changeDescription, 
                        "editor": editor
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_revisionhistoryGet: String { 
        case count&#x3D;none = "count=none"
    }

    /**

     - parameter revisionId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter date: (query)  (optional)
     - parameter changeDescription: (query)  (optional)
     - parameter editor: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func revisionhistoryGet(revisionId: String? = nil, scriptId: String? = nil, date: Date? = nil, changeDescription: String? = nil, editor: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_revisionhistoryGet? = nil, completion: @escaping ((_ data: [Revisionhistory]?,_ error: Error?) -> Void)) {
        revisionhistoryGetWithRequestBuilder(revisionId: revisionId, scriptId: scriptId, date: date, changeDescription: changeDescription, editor: editor, select: select, order: order, range: range, rangeUnit: rangeUnit, offset: offset, limit: limit, prefer: prefer).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /revisionhistory
     - 

     - examples: [{contentType=application/json, example=[ {
  "date" : "2000-01-23",
  "editor" : "editor",
  "change_description" : "change_description",
  "script_id" : 6,
  "revision_id" : 0
}, {
  "date" : "2000-01-23",
  "editor" : "editor",
  "change_description" : "change_description",
  "script_id" : 6,
  "revision_id" : 0
} ]}]
     - parameter revisionId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter date: (query)  (optional)
     - parameter changeDescription: (query)  (optional)
     - parameter editor: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<[Revisionhistory]> 
     */
    open class func revisionhistoryGetWithRequestBuilder(revisionId: String? = nil, scriptId: String? = nil, date: Date? = nil, changeDescription: String? = nil, editor: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_revisionhistoryGet? = nil) -> RequestBuilder<[Revisionhistory]> {
        let path = "/revisionhistory"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "revision_id": revisionId, 
                        "script_id": scriptId, 
                        "date": date?.encodeToJSON(), 
                        "change_description": changeDescription, 
                        "editor": editor, 
                        "select": select, 
                        "order": order, 
                        "offset": offset, 
                        "limit": limit
        ])
        let nillableHeaders: [String: Any?] = [
                        "Range": range,
                        "Range-Unit": rangeUnit,
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[Revisionhistory]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_revisionhistoryPatch: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter body: (body) revisionhistory (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter revisionId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter date: (query)  (optional)
     - parameter changeDescription: (query)  (optional)
     - parameter editor: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func revisionhistoryPatch(body: Revisionhistory? = nil, prefer: Prefer_revisionhistoryPatch? = nil, revisionId: String? = nil, scriptId: String? = nil, date: Date? = nil, changeDescription: String? = nil, editor: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        revisionhistoryPatchWithRequestBuilder(body: body, prefer: prefer, revisionId: revisionId, scriptId: scriptId, date: date, changeDescription: changeDescription, editor: editor).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - PATCH /revisionhistory
     - 

     - parameter body: (body) revisionhistory (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter revisionId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter date: (query)  (optional)
     - parameter changeDescription: (query)  (optional)
     - parameter editor: (query)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func revisionhistoryPatchWithRequestBuilder(body: Revisionhistory? = nil, prefer: Prefer_revisionhistoryPatch? = nil, revisionId: String? = nil, scriptId: String? = nil, date: Date? = nil, changeDescription: String? = nil, editor: String? = nil) -> RequestBuilder<Void> {
        let path = "/revisionhistory"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "revision_id": revisionId, 
                        "script_id": scriptId, 
                        "date": date?.encodeToJSON(), 
                        "change_description": changeDescription, 
                        "editor": editor
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_revisionhistoryPost: String { 
        case return&#x3D;representation = "return=representation"
        case return&#x3D;minimal = "return=minimal"
        case return&#x3D;none = "return=none"
        case resolution&#x3D;ignoreDuplicates = "resolution=ignore-duplicates"
        case resolution&#x3D;mergeDuplicates = "resolution=merge-duplicates"
    }

    /**

     - parameter body: (body) revisionhistory (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func revisionhistoryPost(body: Revisionhistory? = nil, prefer: Prefer_revisionhistoryPost? = nil, select: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        revisionhistoryPostWithRequestBuilder(body: body, prefer: prefer, select: select).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - POST /revisionhistory
     - 

     - parameter body: (body) revisionhistory (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func revisionhistoryPostWithRequestBuilder(body: Revisionhistory? = nil, prefer: Prefer_revisionhistoryPost? = nil, select: String? = nil) -> RequestBuilder<Void> {
        let path = "/revisionhistory"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "select": select
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
}
