//
// ScenelocationAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class ScenelocationAPI {
    /**
     * enum for parameter prefer
     */
    public enum Prefer_scenelocationDelete: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter locationId: (query)  (optional)
     - parameter _description: (query)  (optional)
     - parameter historicalCulturalSignificance: (query)  (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func scenelocationDelete(locationId: String? = nil, _description: String? = nil, historicalCulturalSignificance: String? = nil, prefer: Prefer_scenelocationDelete? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        scenelocationDeleteWithRequestBuilder(locationId: locationId, _description: _description, historicalCulturalSignificance: historicalCulturalSignificance, prefer: prefer).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /scenelocation
     - 

     - parameter locationId: (query)  (optional)
     - parameter _description: (query)  (optional)
     - parameter historicalCulturalSignificance: (query)  (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func scenelocationDeleteWithRequestBuilder(locationId: String? = nil, _description: String? = nil, historicalCulturalSignificance: String? = nil, prefer: Prefer_scenelocationDelete? = nil) -> RequestBuilder<Void> {
        let path = "/scenelocation"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "location_id": locationId, 
                        "description": _description, 
                        "historical_cultural_significance": historicalCulturalSignificance
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_scenelocationGet: String { 
        case count&#x3D;none = "count=none"
    }

    /**

     - parameter locationId: (query)  (optional)
     - parameter _description: (query)  (optional)
     - parameter historicalCulturalSignificance: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func scenelocationGet(locationId: String? = nil, _description: String? = nil, historicalCulturalSignificance: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_scenelocationGet? = nil, completion: @escaping ((_ data: [Scenelocation]?,_ error: Error?) -> Void)) {
        scenelocationGetWithRequestBuilder(locationId: locationId, _description: _description, historicalCulturalSignificance: historicalCulturalSignificance, select: select, order: order, range: range, rangeUnit: rangeUnit, offset: offset, limit: limit, prefer: prefer).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /scenelocation
     - 

     - examples: [{contentType=application/json, example=[ {
  "description" : "description",
  "historical_cultural_significance" : "historical_cultural_significance",
  "location_id" : 0
}, {
  "description" : "description",
  "historical_cultural_significance" : "historical_cultural_significance",
  "location_id" : 0
} ]}]
     - parameter locationId: (query)  (optional)
     - parameter _description: (query)  (optional)
     - parameter historicalCulturalSignificance: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<[Scenelocation]> 
     */
    open class func scenelocationGetWithRequestBuilder(locationId: String? = nil, _description: String? = nil, historicalCulturalSignificance: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_scenelocationGet? = nil) -> RequestBuilder<[Scenelocation]> {
        let path = "/scenelocation"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "location_id": locationId, 
                        "description": _description, 
                        "historical_cultural_significance": historicalCulturalSignificance, 
                        "select": select, 
                        "order": order, 
                        "offset": offset, 
                        "limit": limit
        ])
        let nillableHeaders: [String: Any?] = [
                        "Range": range,
                        "Range-Unit": rangeUnit,
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[Scenelocation]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_scenelocationPatch: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter body: (body) scenelocation (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter locationId: (query)  (optional)
     - parameter _description: (query)  (optional)
     - parameter historicalCulturalSignificance: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func scenelocationPatch(body: Scenelocation? = nil, prefer: Prefer_scenelocationPatch? = nil, locationId: String? = nil, _description: String? = nil, historicalCulturalSignificance: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        scenelocationPatchWithRequestBuilder(body: body, prefer: prefer, locationId: locationId, _description: _description, historicalCulturalSignificance: historicalCulturalSignificance).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - PATCH /scenelocation
     - 

     - parameter body: (body) scenelocation (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter locationId: (query)  (optional)
     - parameter _description: (query)  (optional)
     - parameter historicalCulturalSignificance: (query)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func scenelocationPatchWithRequestBuilder(body: Scenelocation? = nil, prefer: Prefer_scenelocationPatch? = nil, locationId: String? = nil, _description: String? = nil, historicalCulturalSignificance: String? = nil) -> RequestBuilder<Void> {
        let path = "/scenelocation"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "location_id": locationId, 
                        "description": _description, 
                        "historical_cultural_significance": historicalCulturalSignificance
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_scenelocationPost: String { 
        case return&#x3D;representation = "return=representation"
        case return&#x3D;minimal = "return=minimal"
        case return&#x3D;none = "return=none"
        case resolution&#x3D;ignoreDuplicates = "resolution=ignore-duplicates"
        case resolution&#x3D;mergeDuplicates = "resolution=merge-duplicates"
    }

    /**

     - parameter body: (body) scenelocation (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func scenelocationPost(body: Scenelocation? = nil, prefer: Prefer_scenelocationPost? = nil, select: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        scenelocationPostWithRequestBuilder(body: body, prefer: prefer, select: select).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - POST /scenelocation
     - 

     - parameter body: (body) scenelocation (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func scenelocationPostWithRequestBuilder(body: Scenelocation? = nil, prefer: Prefer_scenelocationPost? = nil, select: String? = nil) -> RequestBuilder<Void> {
        let path = "/scenelocation"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "select": select
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
}
