//
// SceneAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class SceneAPI {
    /**
     * enum for parameter prefer
     */
    public enum Prefer_sceneDelete: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter sceneId: (query)  (optional)
     - parameter actId: (query)  (optional)
     - parameter sceneNumber: (query)  (optional)
     - parameter synopsis: (query)  (optional)
     - parameter notes: (query)  (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func sceneDelete(sceneId: String? = nil, actId: String? = nil, sceneNumber: String? = nil, synopsis: String? = nil, notes: String? = nil, prefer: Prefer_sceneDelete? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        sceneDeleteWithRequestBuilder(sceneId: sceneId, actId: actId, sceneNumber: sceneNumber, synopsis: synopsis, notes: notes, prefer: prefer).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /scene
     - 

     - parameter sceneId: (query)  (optional)
     - parameter actId: (query)  (optional)
     - parameter sceneNumber: (query)  (optional)
     - parameter synopsis: (query)  (optional)
     - parameter notes: (query)  (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func sceneDeleteWithRequestBuilder(sceneId: String? = nil, actId: String? = nil, sceneNumber: String? = nil, synopsis: String? = nil, notes: String? = nil, prefer: Prefer_sceneDelete? = nil) -> RequestBuilder<Void> {
        let path = "/scene"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "scene_id": sceneId, 
                        "act_id": actId, 
                        "scene_number": sceneNumber, 
                        "synopsis": synopsis, 
                        "notes": notes
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_sceneGet: String { 
        case count&#x3D;none = "count=none"
    }

    /**

     - parameter sceneId: (query)  (optional)
     - parameter actId: (query)  (optional)
     - parameter sceneNumber: (query)  (optional)
     - parameter synopsis: (query)  (optional)
     - parameter notes: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func sceneGet(sceneId: String? = nil, actId: String? = nil, sceneNumber: String? = nil, synopsis: String? = nil, notes: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_sceneGet? = nil, completion: @escaping ((_ data: [Scene]?,_ error: Error?) -> Void)) {
        sceneGetWithRequestBuilder(sceneId: sceneId, actId: actId, sceneNumber: sceneNumber, synopsis: synopsis, notes: notes, select: select, order: order, range: range, rangeUnit: rangeUnit, offset: offset, limit: limit, prefer: prefer).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /scene
     - 

     - examples: [{contentType=application/json, example=[ {
  "scene_number" : 1,
  "notes" : "notes",
  "act_id" : 6,
  "scene_id" : 0,
  "synopsis" : "synopsis"
}, {
  "scene_number" : 1,
  "notes" : "notes",
  "act_id" : 6,
  "scene_id" : 0,
  "synopsis" : "synopsis"
} ]}]
     - parameter sceneId: (query)  (optional)
     - parameter actId: (query)  (optional)
     - parameter sceneNumber: (query)  (optional)
     - parameter synopsis: (query)  (optional)
     - parameter notes: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<[Scene]> 
     */
    open class func sceneGetWithRequestBuilder(sceneId: String? = nil, actId: String? = nil, sceneNumber: String? = nil, synopsis: String? = nil, notes: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_sceneGet? = nil) -> RequestBuilder<[Scene]> {
        let path = "/scene"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "scene_id": sceneId, 
                        "act_id": actId, 
                        "scene_number": sceneNumber, 
                        "synopsis": synopsis, 
                        "notes": notes, 
                        "select": select, 
                        "order": order, 
                        "offset": offset, 
                        "limit": limit
        ])
        let nillableHeaders: [String: Any?] = [
                        "Range": range,
                        "Range-Unit": rangeUnit,
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[Scene]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_scenePatch: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter body: (body) scene (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter sceneId: (query)  (optional)
     - parameter actId: (query)  (optional)
     - parameter sceneNumber: (query)  (optional)
     - parameter synopsis: (query)  (optional)
     - parameter notes: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func scenePatch(body: Scene? = nil, prefer: Prefer_scenePatch? = nil, sceneId: String? = nil, actId: String? = nil, sceneNumber: String? = nil, synopsis: String? = nil, notes: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        scenePatchWithRequestBuilder(body: body, prefer: prefer, sceneId: sceneId, actId: actId, sceneNumber: sceneNumber, synopsis: synopsis, notes: notes).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - PATCH /scene
     - 

     - parameter body: (body) scene (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter sceneId: (query)  (optional)
     - parameter actId: (query)  (optional)
     - parameter sceneNumber: (query)  (optional)
     - parameter synopsis: (query)  (optional)
     - parameter notes: (query)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func scenePatchWithRequestBuilder(body: Scene? = nil, prefer: Prefer_scenePatch? = nil, sceneId: String? = nil, actId: String? = nil, sceneNumber: String? = nil, synopsis: String? = nil, notes: String? = nil) -> RequestBuilder<Void> {
        let path = "/scene"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "scene_id": sceneId, 
                        "act_id": actId, 
                        "scene_number": sceneNumber, 
                        "synopsis": synopsis, 
                        "notes": notes
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_scenePost: String { 
        case return&#x3D;representation = "return=representation"
        case return&#x3D;minimal = "return=minimal"
        case return&#x3D;none = "return=none"
        case resolution&#x3D;ignoreDuplicates = "resolution=ignore-duplicates"
        case resolution&#x3D;mergeDuplicates = "resolution=merge-duplicates"
    }

    /**

     - parameter body: (body) scene (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func scenePost(body: Scene? = nil, prefer: Prefer_scenePost? = nil, select: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        scenePostWithRequestBuilder(body: body, prefer: prefer, select: select).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - POST /scene
     - 

     - parameter body: (body) scene (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func scenePostWithRequestBuilder(body: Scene? = nil, prefer: Prefer_scenePost? = nil, select: String? = nil) -> RequestBuilder<Void> {
        let path = "/scene"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "select": select
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
}
