//
// SectionheadingAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class SectionheadingAPI {
    /**
     * enum for parameter prefer
     */
    public enum Prefer_sectionheadingDelete: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter sectionId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter text: (query)  (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func sectionheadingDelete(sectionId: String? = nil, scriptId: String? = nil, text: String? = nil, prefer: Prefer_sectionheadingDelete? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        sectionheadingDeleteWithRequestBuilder(sectionId: sectionId, scriptId: scriptId, text: text, prefer: prefer).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /sectionheading
     - 

     - parameter sectionId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter text: (query)  (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func sectionheadingDeleteWithRequestBuilder(sectionId: String? = nil, scriptId: String? = nil, text: String? = nil, prefer: Prefer_sectionheadingDelete? = nil) -> RequestBuilder<Void> {
        let path = "/sectionheading"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "section_id": sectionId, 
                        "script_id": scriptId, 
                        "text": text
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_sectionheadingGet: String { 
        case count&#x3D;none = "count=none"
    }

    /**

     - parameter sectionId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter text: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func sectionheadingGet(sectionId: String? = nil, scriptId: String? = nil, text: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_sectionheadingGet? = nil, completion: @escaping ((_ data: [Sectionheading]?,_ error: Error?) -> Void)) {
        sectionheadingGetWithRequestBuilder(sectionId: sectionId, scriptId: scriptId, text: text, select: select, order: order, range: range, rangeUnit: rangeUnit, offset: offset, limit: limit, prefer: prefer).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /sectionheading
     - 

     - examples: [{contentType=application/json, example=[ {
  "section_id" : 0,
  "script_id" : 6,
  "text" : "text"
}, {
  "section_id" : 0,
  "script_id" : 6,
  "text" : "text"
} ]}]
     - parameter sectionId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter text: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<[Sectionheading]> 
     */
    open class func sectionheadingGetWithRequestBuilder(sectionId: String? = nil, scriptId: String? = nil, text: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_sectionheadingGet? = nil) -> RequestBuilder<[Sectionheading]> {
        let path = "/sectionheading"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "section_id": sectionId, 
                        "script_id": scriptId, 
                        "text": text, 
                        "select": select, 
                        "order": order, 
                        "offset": offset, 
                        "limit": limit
        ])
        let nillableHeaders: [String: Any?] = [
                        "Range": range,
                        "Range-Unit": rangeUnit,
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[Sectionheading]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_sectionheadingPatch: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter body: (body) sectionheading (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter sectionId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter text: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func sectionheadingPatch(body: Sectionheading? = nil, prefer: Prefer_sectionheadingPatch? = nil, sectionId: String? = nil, scriptId: String? = nil, text: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        sectionheadingPatchWithRequestBuilder(body: body, prefer: prefer, sectionId: sectionId, scriptId: scriptId, text: text).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - PATCH /sectionheading
     - 

     - parameter body: (body) sectionheading (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter sectionId: (query)  (optional)
     - parameter scriptId: (query)  (optional)
     - parameter text: (query)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func sectionheadingPatchWithRequestBuilder(body: Sectionheading? = nil, prefer: Prefer_sectionheadingPatch? = nil, sectionId: String? = nil, scriptId: String? = nil, text: String? = nil) -> RequestBuilder<Void> {
        let path = "/sectionheading"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "section_id": sectionId, 
                        "script_id": scriptId, 
                        "text": text
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_sectionheadingPost: String { 
        case return&#x3D;representation = "return=representation"
        case return&#x3D;minimal = "return=minimal"
        case return&#x3D;none = "return=none"
        case resolution&#x3D;ignoreDuplicates = "resolution=ignore-duplicates"
        case resolution&#x3D;mergeDuplicates = "resolution=merge-duplicates"
    }

    /**

     - parameter body: (body) sectionheading (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func sectionheadingPost(body: Sectionheading? = nil, prefer: Prefer_sectionheadingPost? = nil, select: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        sectionheadingPostWithRequestBuilder(body: body, prefer: prefer, select: select).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - POST /sectionheading
     - 

     - parameter body: (body) sectionheading (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func sectionheadingPostWithRequestBuilder(body: Sectionheading? = nil, prefer: Prefer_sectionheadingPost? = nil, select: String? = nil) -> RequestBuilder<Void> {
        let path = "/sectionheading"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "select": select
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
}
