//
// TransitionAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class TransitionAPI {
    /**
     * enum for parameter prefer
     */
    public enum Prefer_transitionDelete: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter transitionId: (query)  (optional)
     - parameter sceneId: (query)  (optional)
     - parameter transitionText: (query)  (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func transitionDelete(transitionId: String? = nil, sceneId: String? = nil, transitionText: String? = nil, prefer: Prefer_transitionDelete? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        transitionDeleteWithRequestBuilder(transitionId: transitionId, sceneId: sceneId, transitionText: transitionText, prefer: prefer).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /transition
     - 

     - parameter transitionId: (query)  (optional)
     - parameter sceneId: (query)  (optional)
     - parameter transitionText: (query)  (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func transitionDeleteWithRequestBuilder(transitionId: String? = nil, sceneId: String? = nil, transitionText: String? = nil, prefer: Prefer_transitionDelete? = nil) -> RequestBuilder<Void> {
        let path = "/transition"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "transition_id": transitionId, 
                        "scene_id": sceneId, 
                        "transition_text": transitionText
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_transitionGet: String { 
        case count&#x3D;none = "count=none"
    }

    /**

     - parameter transitionId: (query)  (optional)
     - parameter sceneId: (query)  (optional)
     - parameter transitionText: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func transitionGet(transitionId: String? = nil, sceneId: String? = nil, transitionText: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_transitionGet? = nil, completion: @escaping ((_ data: [Transition]?,_ error: Error?) -> Void)) {
        transitionGetWithRequestBuilder(transitionId: transitionId, sceneId: sceneId, transitionText: transitionText, select: select, order: order, range: range, rangeUnit: rangeUnit, offset: offset, limit: limit, prefer: prefer).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /transition
     - 

     - examples: [{contentType=application/json, example=[ {
  "scene_id" : 6,
  "transition_text" : "transition_text",
  "transition_id" : 0
}, {
  "scene_id" : 6,
  "transition_text" : "transition_text",
  "transition_id" : 0
} ]}]
     - parameter transitionId: (query)  (optional)
     - parameter sceneId: (query)  (optional)
     - parameter transitionText: (query)  (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter order: (query) Ordering (optional)
     - parameter range: (header) Limiting and Pagination (optional)
     - parameter rangeUnit: (header) Limiting and Pagination (optional, default to items)
     - parameter offset: (query) Limiting and Pagination (optional)
     - parameter limit: (query) Limiting and Pagination (optional)
     - parameter prefer: (header) Preference (optional)

     - returns: RequestBuilder<[Transition]> 
     */
    open class func transitionGetWithRequestBuilder(transitionId: String? = nil, sceneId: String? = nil, transitionText: String? = nil, select: String? = nil, order: String? = nil, range: String? = nil, rangeUnit: String? = nil, offset: String? = nil, limit: String? = nil, prefer: Prefer_transitionGet? = nil) -> RequestBuilder<[Transition]> {
        let path = "/transition"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "transition_id": transitionId, 
                        "scene_id": sceneId, 
                        "transition_text": transitionText, 
                        "select": select, 
                        "order": order, 
                        "offset": offset, 
                        "limit": limit
        ])
        let nillableHeaders: [String: Any?] = [
                        "Range": range,
                        "Range-Unit": rangeUnit,
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<[Transition]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_transitionPatch: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
        case _none = "return=none"
    }

    /**

     - parameter body: (body) transition (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter transitionId: (query)  (optional)
     - parameter sceneId: (query)  (optional)
     - parameter transitionText: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func transitionPatch(body: Transition? = nil, prefer: Prefer_transitionPatch? = nil, transitionId: String? = nil, sceneId: String? = nil, transitionText: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        transitionPatchWithRequestBuilder(body: body, prefer: prefer, transitionId: transitionId, sceneId: sceneId, transitionText: transitionText).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - PATCH /transition
     - 

     - parameter body: (body) transition (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter transitionId: (query)  (optional)
     - parameter sceneId: (query)  (optional)
     - parameter transitionText: (query)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func transitionPatchWithRequestBuilder(body: Transition? = nil, prefer: Prefer_transitionPatch? = nil, transitionId: String? = nil, sceneId: String? = nil, transitionText: String? = nil) -> RequestBuilder<Void> {
        let path = "/transition"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "transition_id": transitionId, 
                        "scene_id": sceneId, 
                        "transition_text": transitionText
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
    /**
     * enum for parameter prefer
     */
    public enum Prefer_transitionPost: String { 
        case return&#x3D;representation = "return=representation"
        case return&#x3D;minimal = "return=minimal"
        case return&#x3D;none = "return=none"
        case resolution&#x3D;ignoreDuplicates = "resolution=ignore-duplicates"
        case resolution&#x3D;mergeDuplicates = "resolution=merge-duplicates"
    }

    /**

     - parameter body: (body) transition (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func transitionPost(body: Transition? = nil, prefer: Prefer_transitionPost? = nil, select: String? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        transitionPostWithRequestBuilder(body: body, prefer: prefer, select: select).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - POST /transition
     - 

     - parameter body: (body) transition (optional)
     - parameter prefer: (header) Preference (optional)
     - parameter select: (query) Filtering Columns (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func transitionPostWithRequestBuilder(body: Transition? = nil, prefer: Prefer_transitionPost? = nil, select: String? = nil) -> RequestBuilder<Void> {
        let path = "/transition"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "select": select
        ])
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
}
