# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Act(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, act_id: int=None, script_id: int=None, act_number: int=None, synopsis: str=None, notes: str=None):  # noqa: E501
        """Act - a model defined in Swagger

        :param act_id: The act_id of this Act.  # noqa: E501
        :type act_id: int
        :param script_id: The script_id of this Act.  # noqa: E501
        :type script_id: int
        :param act_number: The act_number of this Act.  # noqa: E501
        :type act_number: int
        :param synopsis: The synopsis of this Act.  # noqa: E501
        :type synopsis: str
        :param notes: The notes of this Act.  # noqa: E501
        :type notes: str
        """
        self.swagger_types = {
            'act_id': int,
            'script_id': int,
            'act_number': int,
            'synopsis': str,
            'notes': str
        }

        self.attribute_map = {
            'act_id': 'act_id',
            'script_id': 'script_id',
            'act_number': 'act_number',
            'synopsis': 'synopsis',
            'notes': 'notes'
        }
        self._act_id = act_id
        self._script_id = script_id
        self._act_number = act_number
        self._synopsis = synopsis
        self._notes = notes

    @classmethod
    def from_dict(cls, dikt) -> 'Act':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The act of this Act.  # noqa: E501
        :rtype: Act
        """
        return util.deserialize_model(dikt, cls)

    @property
    def act_id(self) -> int:
        """Gets the act_id of this Act.

        Note: This is a Primary Key.<pk/>  # noqa: E501

        :return: The act_id of this Act.
        :rtype: int
        """
        return self._act_id

    @act_id.setter
    def act_id(self, act_id: int):
        """Sets the act_id of this Act.

        Note: This is a Primary Key.<pk/>  # noqa: E501

        :param act_id: The act_id of this Act.
        :type act_id: int
        """
        if act_id is None:
            raise ValueError("Invalid value for `act_id`, must not be `None`")  # noqa: E501

        self._act_id = act_id

    @property
    def script_id(self) -> int:
        """Gets the script_id of this Act.

        Note: This is a Foreign Key to `script.script_id`.<fk table='script' column='script_id'/>  # noqa: E501

        :return: The script_id of this Act.
        :rtype: int
        """
        return self._script_id

    @script_id.setter
    def script_id(self, script_id: int):
        """Sets the script_id of this Act.

        Note: This is a Foreign Key to `script.script_id`.<fk table='script' column='script_id'/>  # noqa: E501

        :param script_id: The script_id of this Act.
        :type script_id: int
        """

        self._script_id = script_id

    @property
    def act_number(self) -> int:
        """Gets the act_number of this Act.


        :return: The act_number of this Act.
        :rtype: int
        """
        return self._act_number

    @act_number.setter
    def act_number(self, act_number: int):
        """Sets the act_number of this Act.


        :param act_number: The act_number of this Act.
        :type act_number: int
        """
        if act_number is None:
            raise ValueError("Invalid value for `act_number`, must not be `None`")  # noqa: E501

        self._act_number = act_number

    @property
    def synopsis(self) -> str:
        """Gets the synopsis of this Act.


        :return: The synopsis of this Act.
        :rtype: str
        """
        return self._synopsis

    @synopsis.setter
    def synopsis(self, synopsis: str):
        """Sets the synopsis of this Act.


        :param synopsis: The synopsis of this Act.
        :type synopsis: str
        """

        self._synopsis = synopsis

    @property
    def notes(self) -> str:
        """Gets the notes of this Act.


        :return: The notes of this Act.
        :rtype: str
        """
        return self._notes

    @notes.setter
    def notes(self, notes: str):
        """Sets the notes of this Act.


        :param notes: The notes of this Act.
        :type notes: str
        """

        self._notes = notes
