# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Metadata(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, metadata_id: int=None, creation_date: date=None, last_modified_date: date=None, version_number: int=None, additional_information: str=None):  # noqa: E501
        """Metadata - a model defined in Swagger

        :param metadata_id: The metadata_id of this Metadata.  # noqa: E501
        :type metadata_id: int
        :param creation_date: The creation_date of this Metadata.  # noqa: E501
        :type creation_date: date
        :param last_modified_date: The last_modified_date of this Metadata.  # noqa: E501
        :type last_modified_date: date
        :param version_number: The version_number of this Metadata.  # noqa: E501
        :type version_number: int
        :param additional_information: The additional_information of this Metadata.  # noqa: E501
        :type additional_information: str
        """
        self.swagger_types = {
            'metadata_id': int,
            'creation_date': date,
            'last_modified_date': date,
            'version_number': int,
            'additional_information': str
        }

        self.attribute_map = {
            'metadata_id': 'metadata_id',
            'creation_date': 'creation_date',
            'last_modified_date': 'last_modified_date',
            'version_number': 'version_number',
            'additional_information': 'additional_information'
        }
        self._metadata_id = metadata_id
        self._creation_date = creation_date
        self._last_modified_date = last_modified_date
        self._version_number = version_number
        self._additional_information = additional_information

    @classmethod
    def from_dict(cls, dikt) -> 'Metadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The metadata of this Metadata.  # noqa: E501
        :rtype: Metadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata_id(self) -> int:
        """Gets the metadata_id of this Metadata.

        Note: This is a Primary Key.<pk/>  # noqa: E501

        :return: The metadata_id of this Metadata.
        :rtype: int
        """
        return self._metadata_id

    @metadata_id.setter
    def metadata_id(self, metadata_id: int):
        """Sets the metadata_id of this Metadata.

        Note: This is a Primary Key.<pk/>  # noqa: E501

        :param metadata_id: The metadata_id of this Metadata.
        :type metadata_id: int
        """
        if metadata_id is None:
            raise ValueError("Invalid value for `metadata_id`, must not be `None`")  # noqa: E501

        self._metadata_id = metadata_id

    @property
    def creation_date(self) -> date:
        """Gets the creation_date of this Metadata.


        :return: The creation_date of this Metadata.
        :rtype: date
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date: date):
        """Sets the creation_date of this Metadata.


        :param creation_date: The creation_date of this Metadata.
        :type creation_date: date
        """

        self._creation_date = creation_date

    @property
    def last_modified_date(self) -> date:
        """Gets the last_modified_date of this Metadata.


        :return: The last_modified_date of this Metadata.
        :rtype: date
        """
        return self._last_modified_date

    @last_modified_date.setter
    def last_modified_date(self, last_modified_date: date):
        """Sets the last_modified_date of this Metadata.


        :param last_modified_date: The last_modified_date of this Metadata.
        :type last_modified_date: date
        """

        self._last_modified_date = last_modified_date

    @property
    def version_number(self) -> int:
        """Gets the version_number of this Metadata.


        :return: The version_number of this Metadata.
        :rtype: int
        """
        return self._version_number

    @version_number.setter
    def version_number(self, version_number: int):
        """Sets the version_number of this Metadata.


        :param version_number: The version_number of this Metadata.
        :type version_number: int
        """

        self._version_number = version_number

    @property
    def additional_information(self) -> str:
        """Gets the additional_information of this Metadata.


        :return: The additional_information of this Metadata.
        :rtype: str
        """
        return self._additional_information

    @additional_information.setter
    def additional_information(self, additional_information: str):
        """Sets the additional_information of this Metadata.


        :param additional_information: The additional_information of this Metadata.
        :type additional_information: str
        """

        self._additional_information = additional_information
