# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Musicsound(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, music_sound_id: int=None, scene_id: int=None, cue: str=None, description: str=None):  # noqa: E501
        """Musicsound - a model defined in Swagger

        :param music_sound_id: The music_sound_id of this Musicsound.  # noqa: E501
        :type music_sound_id: int
        :param scene_id: The scene_id of this Musicsound.  # noqa: E501
        :type scene_id: int
        :param cue: The cue of this Musicsound.  # noqa: E501
        :type cue: str
        :param description: The description of this Musicsound.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'music_sound_id': int,
            'scene_id': int,
            'cue': str,
            'description': str
        }

        self.attribute_map = {
            'music_sound_id': 'music_sound_id',
            'scene_id': 'scene_id',
            'cue': 'cue',
            'description': 'description'
        }
        self._music_sound_id = music_sound_id
        self._scene_id = scene_id
        self._cue = cue
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'Musicsound':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The musicsound of this Musicsound.  # noqa: E501
        :rtype: Musicsound
        """
        return util.deserialize_model(dikt, cls)

    @property
    def music_sound_id(self) -> int:
        """Gets the music_sound_id of this Musicsound.

        Note: This is a Primary Key.<pk/>  # noqa: E501

        :return: The music_sound_id of this Musicsound.
        :rtype: int
        """
        return self._music_sound_id

    @music_sound_id.setter
    def music_sound_id(self, music_sound_id: int):
        """Sets the music_sound_id of this Musicsound.

        Note: This is a Primary Key.<pk/>  # noqa: E501

        :param music_sound_id: The music_sound_id of this Musicsound.
        :type music_sound_id: int
        """
        if music_sound_id is None:
            raise ValueError("Invalid value for `music_sound_id`, must not be `None`")  # noqa: E501

        self._music_sound_id = music_sound_id

    @property
    def scene_id(self) -> int:
        """Gets the scene_id of this Musicsound.

        Note: This is a Foreign Key to `scene.scene_id`.<fk table='scene' column='scene_id'/>  # noqa: E501

        :return: The scene_id of this Musicsound.
        :rtype: int
        """
        return self._scene_id

    @scene_id.setter
    def scene_id(self, scene_id: int):
        """Sets the scene_id of this Musicsound.

        Note: This is a Foreign Key to `scene.scene_id`.<fk table='scene' column='scene_id'/>  # noqa: E501

        :param scene_id: The scene_id of this Musicsound.
        :type scene_id: int
        """

        self._scene_id = scene_id

    @property
    def cue(self) -> str:
        """Gets the cue of this Musicsound.


        :return: The cue of this Musicsound.
        :rtype: str
        """
        return self._cue

    @cue.setter
    def cue(self, cue: str):
        """Sets the cue of this Musicsound.


        :param cue: The cue of this Musicsound.
        :type cue: str
        """

        self._cue = cue

    @property
    def description(self) -> str:
        """Gets the description of this Musicsound.


        :return: The description of this Musicsound.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Musicsound.


        :param description: The description of this Musicsound.
        :type description: str
        """

        self._description = description
