# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Props(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, prop_id: int=None, scene_id: int=None, description: str=None):  # noqa: E501
        """Props - a model defined in Swagger

        :param prop_id: The prop_id of this Props.  # noqa: E501
        :type prop_id: int
        :param scene_id: The scene_id of this Props.  # noqa: E501
        :type scene_id: int
        :param description: The description of this Props.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'prop_id': int,
            'scene_id': int,
            'description': str
        }

        self.attribute_map = {
            'prop_id': 'prop_id',
            'scene_id': 'scene_id',
            'description': 'description'
        }
        self._prop_id = prop_id
        self._scene_id = scene_id
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'Props':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The props of this Props.  # noqa: E501
        :rtype: Props
        """
        return util.deserialize_model(dikt, cls)

    @property
    def prop_id(self) -> int:
        """Gets the prop_id of this Props.

        Note: This is a Primary Key.<pk/>  # noqa: E501

        :return: The prop_id of this Props.
        :rtype: int
        """
        return self._prop_id

    @prop_id.setter
    def prop_id(self, prop_id: int):
        """Sets the prop_id of this Props.

        Note: This is a Primary Key.<pk/>  # noqa: E501

        :param prop_id: The prop_id of this Props.
        :type prop_id: int
        """
        if prop_id is None:
            raise ValueError("Invalid value for `prop_id`, must not be `None`")  # noqa: E501

        self._prop_id = prop_id

    @property
    def scene_id(self) -> int:
        """Gets the scene_id of this Props.

        Note: This is a Foreign Key to `scene.scene_id`.<fk table='scene' column='scene_id'/>  # noqa: E501

        :return: The scene_id of this Props.
        :rtype: int
        """
        return self._scene_id

    @scene_id.setter
    def scene_id(self, scene_id: int):
        """Sets the scene_id of this Props.

        Note: This is a Foreign Key to `scene.scene_id`.<fk table='scene' column='scene_id'/>  # noqa: E501

        :param scene_id: The scene_id of this Props.
        :type scene_id: int
        """

        self._scene_id = scene_id

    @property
    def description(self) -> str:
        """Gets the description of this Props.


        :return: The description of this Props.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Props.


        :param description: The description of this Props.
        :type description: str
        """

        self._description = description
