# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Titlepage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title_page_id: int=None, script_id: int=None, text: str=None):  # noqa: E501
        """Titlepage - a model defined in Swagger

        :param title_page_id: The title_page_id of this Titlepage.  # noqa: E501
        :type title_page_id: int
        :param script_id: The script_id of this Titlepage.  # noqa: E501
        :type script_id: int
        :param text: The text of this Titlepage.  # noqa: E501
        :type text: str
        """
        self.swagger_types = {
            'title_page_id': int,
            'script_id': int,
            'text': str
        }

        self.attribute_map = {
            'title_page_id': 'title_page_id',
            'script_id': 'script_id',
            'text': 'text'
        }
        self._title_page_id = title_page_id
        self._script_id = script_id
        self._text = text

    @classmethod
    def from_dict(cls, dikt) -> 'Titlepage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The titlepage of this Titlepage.  # noqa: E501
        :rtype: Titlepage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title_page_id(self) -> int:
        """Gets the title_page_id of this Titlepage.

        Note: This is a Primary Key.<pk/>  # noqa: E501

        :return: The title_page_id of this Titlepage.
        :rtype: int
        """
        return self._title_page_id

    @title_page_id.setter
    def title_page_id(self, title_page_id: int):
        """Sets the title_page_id of this Titlepage.

        Note: This is a Primary Key.<pk/>  # noqa: E501

        :param title_page_id: The title_page_id of this Titlepage.
        :type title_page_id: int
        """
        if title_page_id is None:
            raise ValueError("Invalid value for `title_page_id`, must not be `None`")  # noqa: E501

        self._title_page_id = title_page_id

    @property
    def script_id(self) -> int:
        """Gets the script_id of this Titlepage.

        Note: This is a Foreign Key to `script.script_id`.<fk table='script' column='script_id'/>  # noqa: E501

        :return: The script_id of this Titlepage.
        :rtype: int
        """
        return self._script_id

    @script_id.setter
    def script_id(self, script_id: int):
        """Sets the script_id of this Titlepage.

        Note: This is a Foreign Key to `script.script_id`.<fk table='script' column='script_id'/>  # noqa: E501

        :param script_id: The script_id of this Titlepage.
        :type script_id: int
        """

        self._script_id = script_id

    @property
    def text(self) -> str:
        """Gets the text of this Titlepage.


        :return: The text of this Titlepage.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this Titlepage.


        :param text: The text of this Titlepage.
        :type text: str
        """

        self._text = text
