# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Transition(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, transition_id: int=None, scene_id: int=None, transition_text: str=None):  # noqa: E501
        """Transition - a model defined in Swagger

        :param transition_id: The transition_id of this Transition.  # noqa: E501
        :type transition_id: int
        :param scene_id: The scene_id of this Transition.  # noqa: E501
        :type scene_id: int
        :param transition_text: The transition_text of this Transition.  # noqa: E501
        :type transition_text: str
        """
        self.swagger_types = {
            'transition_id': int,
            'scene_id': int,
            'transition_text': str
        }

        self.attribute_map = {
            'transition_id': 'transition_id',
            'scene_id': 'scene_id',
            'transition_text': 'transition_text'
        }
        self._transition_id = transition_id
        self._scene_id = scene_id
        self._transition_text = transition_text

    @classmethod
    def from_dict(cls, dikt) -> 'Transition':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The transition of this Transition.  # noqa: E501
        :rtype: Transition
        """
        return util.deserialize_model(dikt, cls)

    @property
    def transition_id(self) -> int:
        """Gets the transition_id of this Transition.

        Note: This is a Primary Key.<pk/>  # noqa: E501

        :return: The transition_id of this Transition.
        :rtype: int
        """
        return self._transition_id

    @transition_id.setter
    def transition_id(self, transition_id: int):
        """Sets the transition_id of this Transition.

        Note: This is a Primary Key.<pk/>  # noqa: E501

        :param transition_id: The transition_id of this Transition.
        :type transition_id: int
        """
        if transition_id is None:
            raise ValueError("Invalid value for `transition_id`, must not be `None`")  # noqa: E501

        self._transition_id = transition_id

    @property
    def scene_id(self) -> int:
        """Gets the scene_id of this Transition.

        Note: This is a Foreign Key to `scene.scene_id`.<fk table='scene' column='scene_id'/>  # noqa: E501

        :return: The scene_id of this Transition.
        :rtype: int
        """
        return self._scene_id

    @scene_id.setter
    def scene_id(self, scene_id: int):
        """Sets the scene_id of this Transition.

        Note: This is a Foreign Key to `scene.scene_id`.<fk table='scene' column='scene_id'/>  # noqa: E501

        :param scene_id: The scene_id of this Transition.
        :type scene_id: int
        """

        self._scene_id = scene_id

    @property
    def transition_text(self) -> str:
        """Gets the transition_text of this Transition.


        :return: The transition_text of this Transition.
        :rtype: str
        """
        return self._transition_text

    @transition_text.setter
    def transition_text(self, transition_text: str):
        """Sets the transition_text of this Transition.


        :param transition_text: The transition_text of this Transition.
        :type transition_text: str
        """

        self._transition_text = transition_text
