//
// Act.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Act: Codable {

    /** Note: This is a Primary Key.&lt;pk/&gt; */
    public var actId: Int
    /** Note: This is a Foreign Key to &#x60;script.script_id&#x60;.&lt;fk table&#x3D;&#x27;script&#x27; column&#x3D;&#x27;script_id&#x27;/&gt; */
    public var scriptId: Int?
    public var actNumber: Int
    public var synopsis: String?
    public var notes: String?

    public init(actId: Int, scriptId: Int? = nil, actNumber: Int, synopsis: String? = nil, notes: String? = nil) {
        self.actId = actId
        self.scriptId = scriptId
        self.actNumber = actNumber
        self.synopsis = synopsis
        self.notes = notes
    }

    public enum CodingKeys: String, CodingKey { 
        case actId = "act_id"
        case scriptId = "script_id"
        case actNumber = "act_number"
        case synopsis
        case notes
    }

}
