//
// Casting.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Casting: Codable {

    /** Note: This is a Primary Key.&lt;pk/&gt; */
    public var castingId: Int
    /** Note: This is a Foreign Key to &#x60;character.character_id&#x60;.&lt;fk table&#x3D;&#x27;character&#x27; column&#x3D;&#x27;character_id&#x27;/&gt; */
    public var characterId: Int?
    public var actorCharacteristicsChoices: String?

    public init(castingId: Int, characterId: Int? = nil, actorCharacteristicsChoices: String? = nil) {
        self.castingId = castingId
        self.characterId = characterId
        self.actorCharacteristicsChoices = actorCharacteristicsChoices
    }

    public enum CodingKeys: String, CodingKey { 
        case castingId = "casting_id"
        case characterId = "character_id"
        case actorCharacteristicsChoices = "actor_characteristics_choices"
    }

}
