//
// Characterrelationship.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Characterrelationship: Codable {

    /** Note: This is a Primary Key.&lt;pk/&gt; */
    public var relationshipId: Int
    /** Note: This is a Foreign Key to &#x60;character.character_id&#x60;.&lt;fk table&#x3D;&#x27;character&#x27; column&#x3D;&#x27;character_id&#x27;/&gt; */
    public var character1Id: Int?
    /** Note: This is a Foreign Key to &#x60;character.character_id&#x60;.&lt;fk table&#x3D;&#x27;character&#x27; column&#x3D;&#x27;character_id&#x27;/&gt; */
    public var character2Id: Int?
    public var relationshipType: String?

    public init(relationshipId: Int, character1Id: Int? = nil, character2Id: Int? = nil, relationshipType: String? = nil) {
        self.relationshipId = relationshipId
        self.character1Id = character1Id
        self.character2Id = character2Id
        self.relationshipType = relationshipType
    }

    public enum CodingKeys: String, CodingKey { 
        case relationshipId = "relationship_id"
        case character1Id = "character1_id"
        case character2Id = "character2_id"
        case relationshipType = "relationship_type"
    }

}
