//
// Dialogue.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Dialogue: Codable {

    /** Note: This is a Primary Key.&lt;pk/&gt; */
    public var dialogueId: Int
    /** Note: This is a Foreign Key to &#x60;scene.scene_id&#x60;.&lt;fk table&#x3D;&#x27;scene&#x27; column&#x3D;&#x27;scene_id&#x27;/&gt; */
    public var sceneId: Int?
    /** Note: This is a Foreign Key to &#x60;character.character_id&#x60;.&lt;fk table&#x3D;&#x27;character&#x27; column&#x3D;&#x27;character_id&#x27;/&gt; */
    public var characterId: Int?
    public var originalText: String?
    public var modernizedText: String?

    public init(dialogueId: Int, sceneId: Int? = nil, characterId: Int? = nil, originalText: String? = nil, modernizedText: String? = nil) {
        self.dialogueId = dialogueId
        self.sceneId = sceneId
        self.characterId = characterId
        self.originalText = originalText
        self.modernizedText = modernizedText
    }

    public enum CodingKeys: String, CodingKey { 
        case dialogueId = "dialogue_id"
        case sceneId = "scene_id"
        case characterId = "character_id"
        case originalText = "original_text"
        case modernizedText = "modernized_text"
    }

}
