//
// Extendednotesresearch.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Extendednotesresearch: Codable {

    /** Note: This is a Primary Key.&lt;pk/&gt; */
    public var researchId: Int
    /** Note: This is a Foreign Key to &#x60;script.script_id&#x60;.&lt;fk table&#x3D;&#x27;script&#x27; column&#x3D;&#x27;script_id&#x27;/&gt; */
    public var scriptId: Int?
    public var notes: String?
    public var researchDetails: String?

    public init(researchId: Int, scriptId: Int? = nil, notes: String? = nil, researchDetails: String? = nil) {
        self.researchId = researchId
        self.scriptId = scriptId
        self.notes = notes
        self.researchDetails = researchDetails
    }

    public enum CodingKeys: String, CodingKey { 
        case researchId = "research_id"
        case scriptId = "script_id"
        case notes
        case researchDetails = "research_details"
    }

}
