//
// Formattingrules.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Formattingrules: Codable {

    /** Note: This is a Primary Key.&lt;pk/&gt; */
    public var ruleId: Int
    /** Note: This is a Foreign Key to &#x60;script.script_id&#x60;.&lt;fk table&#x3D;&#x27;script&#x27; column&#x3D;&#x27;script_id&#x27;/&gt; */
    public var scriptId: Int?
    public var ruleDescription: String?

    public init(ruleId: Int, scriptId: Int? = nil, ruleDescription: String? = nil) {
        self.ruleId = ruleId
        self.scriptId = scriptId
        self.ruleDescription = ruleDescription
    }

    public enum CodingKeys: String, CodingKey { 
        case ruleId = "rule_id"
        case scriptId = "script_id"
        case ruleDescription = "rule_description"
    }

}
