//
// Metadata.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Metadata: Codable {

    /** Note: This is a Primary Key.&lt;pk/&gt; */
    public var metadataId: Int
    public var creationDate: Date?
    public var lastModifiedDate: Date?
    public var versionNumber: Int?
    public var additionalInformation: String?

    public init(metadataId: Int, creationDate: Date? = nil, lastModifiedDate: Date? = nil, versionNumber: Int? = nil, additionalInformation: String? = nil) {
        self.metadataId = metadataId
        self.creationDate = creationDate
        self.lastModifiedDate = lastModifiedDate
        self.versionNumber = versionNumber
        self.additionalInformation = additionalInformation
    }

    public enum CodingKeys: String, CodingKey { 
        case metadataId = "metadata_id"
        case creationDate = "creation_date"
        case lastModifiedDate = "last_modified_date"
        case versionNumber = "version_number"
        case additionalInformation = "additional_information"
    }

}
