//
// ModelCharacter.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ModelCharacter: Codable {

    /** Note: This is a Primary Key.&lt;pk/&gt; */
    public var characterId: Int
    /** Note: This is a Foreign Key to &#x60;script.script_id&#x60;.&lt;fk table&#x3D;&#x27;script&#x27; column&#x3D;&#x27;script_id&#x27;/&gt; */
    public var scriptId: Int?
    public var name: String
    public var _description: String?

    public init(characterId: Int, scriptId: Int? = nil, name: String, _description: String? = nil) {
        self.characterId = characterId
        self.scriptId = scriptId
        self.name = name
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case characterId = "character_id"
        case scriptId = "script_id"
        case name
        case _description = "description"
    }

}
