//
// Musicsound.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Musicsound: Codable {

    /** Note: This is a Primary Key.&lt;pk/&gt; */
    public var musicSoundId: Int
    /** Note: This is a Foreign Key to &#x60;scene.scene_id&#x60;.&lt;fk table&#x3D;&#x27;scene&#x27; column&#x3D;&#x27;scene_id&#x27;/&gt; */
    public var sceneId: Int?
    public var cue: String?
    public var _description: String?

    public init(musicSoundId: Int, sceneId: Int? = nil, cue: String? = nil, _description: String? = nil) {
        self.musicSoundId = musicSoundId
        self.sceneId = sceneId
        self.cue = cue
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case musicSoundId = "music_sound_id"
        case sceneId = "scene_id"
        case cue
        case _description = "description"
    }

}
