//
// Parenthetical.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Parenthetical: Codable {

    /** Note: This is a Primary Key.&lt;pk/&gt; */
    public var parentheticalId: Int
    /** Note: This is a Foreign Key to &#x60;dialogue.dialogue_id&#x60;.&lt;fk table&#x3D;&#x27;dialogue&#x27; column&#x3D;&#x27;dialogue_id&#x27;/&gt; */
    public var dialogueId: Int?
    public var originalText: String?
    public var modernizedText: String?

    public init(parentheticalId: Int, dialogueId: Int? = nil, originalText: String? = nil, modernizedText: String? = nil) {
        self.parentheticalId = parentheticalId
        self.dialogueId = dialogueId
        self.originalText = originalText
        self.modernizedText = modernizedText
    }

    public enum CodingKeys: String, CodingKey { 
        case parentheticalId = "parenthetical_id"
        case dialogueId = "dialogue_id"
        case originalText = "original_text"
        case modernizedText = "modernized_text"
    }

}
