//
// Playwright.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Playwright: Codable {

    /** Note: This is a Primary Key.&lt;pk/&gt; */
    public var authorId: Int
    public var name: String
    public var biography: String?
    public var contactInformation: String?

    public init(authorId: Int, name: String, biography: String? = nil, contactInformation: String? = nil) {
        self.authorId = authorId
        self.name = name
        self.biography = biography
        self.contactInformation = contactInformation
    }

    public enum CodingKeys: String, CodingKey { 
        case authorId = "author_id"
        case name
        case biography
        case contactInformation = "contact_information"
    }

}
