//
// Props.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Props: Codable {

    /** Note: This is a Primary Key.&lt;pk/&gt; */
    public var propId: Int
    /** Note: This is a Foreign Key to &#x60;scene.scene_id&#x60;.&lt;fk table&#x3D;&#x27;scene&#x27; column&#x3D;&#x27;scene_id&#x27;/&gt; */
    public var sceneId: Int?
    public var _description: String?

    public init(propId: Int, sceneId: Int? = nil, _description: String? = nil) {
        self.propId = propId
        self.sceneId = sceneId
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case propId = "prop_id"
        case sceneId = "scene_id"
        case _description = "description"
    }

}
