//
// Revisionhistory.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Revisionhistory: Codable {

    /** Note: This is a Primary Key.&lt;pk/&gt; */
    public var revisionId: Int
    /** Note: This is a Foreign Key to &#x60;script.script_id&#x60;.&lt;fk table&#x3D;&#x27;script&#x27; column&#x3D;&#x27;script_id&#x27;/&gt; */
    public var scriptId: Int?
    public var date: Date?
    public var changeDescription: String?
    public var editor: String?

    public init(revisionId: Int, scriptId: Int? = nil, date: Date? = nil, changeDescription: String? = nil, editor: String? = nil) {
        self.revisionId = revisionId
        self.scriptId = scriptId
        self.date = date
        self.changeDescription = changeDescription
        self.editor = editor
    }

    public enum CodingKeys: String, CodingKey { 
        case revisionId = "revision_id"
        case scriptId = "script_id"
        case date
        case changeDescription = "change_description"
        case editor
    }

}
