//
// Scene.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Scene: Codable {

    /** Note: This is a Primary Key.&lt;pk/&gt; */
    public var sceneId: Int
    /** Note: This is a Foreign Key to &#x60;act.act_id&#x60;.&lt;fk table&#x3D;&#x27;act&#x27; column&#x3D;&#x27;act_id&#x27;/&gt; */
    public var actId: Int?
    public var sceneNumber: Int
    public var synopsis: String?
    public var notes: String?

    public init(sceneId: Int, actId: Int? = nil, sceneNumber: Int, synopsis: String? = nil, notes: String? = nil) {
        self.sceneId = sceneId
        self.actId = actId
        self.sceneNumber = sceneNumber
        self.synopsis = synopsis
        self.notes = notes
    }

    public enum CodingKeys: String, CodingKey { 
        case sceneId = "scene_id"
        case actId = "act_id"
        case sceneNumber = "scene_number"
        case synopsis
        case notes
    }

}
