//
// Scenelocation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Scenelocation: Codable {

    /** Note: This is a Primary Key.&lt;pk/&gt; */
    public var locationId: Int
    public var _description: String
    public var historicalCulturalSignificance: String?

    public init(locationId: Int, _description: String, historicalCulturalSignificance: String? = nil) {
        self.locationId = locationId
        self._description = _description
        self.historicalCulturalSignificance = historicalCulturalSignificance
    }

    public enum CodingKeys: String, CodingKey { 
        case locationId = "location_id"
        case _description = "description"
        case historicalCulturalSignificance = "historical_cultural_significance"
    }

}
