//
// Script.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Script: Codable {

    /** Note: This is a Primary Key.&lt;pk/&gt; */
    public var scriptId: Int
    public var title: String
    /** Note: This is a Foreign Key to &#x60;playwright.author_id&#x60;.&lt;fk table&#x3D;&#x27;playwright&#x27; column&#x3D;&#x27;author_id&#x27;/&gt; */
    public var authorId: Int?
    public var url: String?
    /** Note: This is a Foreign Key to &#x60;metadata.metadata_id&#x60;.&lt;fk table&#x3D;&#x27;metadata&#x27; column&#x3D;&#x27;metadata_id&#x27;/&gt; */
    public var metadataId: Int?

    public init(scriptId: Int, title: String, authorId: Int? = nil, url: String? = nil, metadataId: Int? = nil) {
        self.scriptId = scriptId
        self.title = title
        self.authorId = authorId
        self.url = url
        self.metadataId = metadataId
    }

    public enum CodingKeys: String, CodingKey { 
        case scriptId = "script_id"
        case title
        case authorId = "author_id"
        case url
        case metadataId = "metadata_id"
    }

}
