//
// Transition.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Transition: Codable {

    /** Note: This is a Primary Key.&lt;pk/&gt; */
    public var transitionId: Int
    /** Note: This is a Foreign Key to &#x60;scene.scene_id&#x60;.&lt;fk table&#x3D;&#x27;scene&#x27; column&#x3D;&#x27;scene_id&#x27;/&gt; */
    public var sceneId: Int?
    public var transitionText: String?

    public init(transitionId: Int, sceneId: Int? = nil, transitionText: String? = nil) {
        self.transitionId = transitionId
        self.sceneId = sceneId
        self.transitionText = transitionText
    }

    public enum CodingKeys: String, CodingKey { 
        case transitionId = "transition_id"
        case sceneId = "scene_id"
        case transitionText = "transition_text"
    }

}
